services:
  influxdb2:
    image: influxdb:2.7
    restart: always
    container_name: influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=local
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors
    volumes:
      - influxdb2-etc-storage:/etc/influxdb2
      - influxdb2-storage:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.32-alpine
    restart: always
    container_name: telegraf
    ports:
      - "7080:7080"
    links:
      - influxdb2
      - mosquitto
    env_file:
      - path: secrets.env
        required: true
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:11.2.2
    restart: always
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb2
    depends_on:
      - influxdb2
    volumes:
      - grafana-storage:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always    
    hostname: mosquitto
    container_name: mosquitto
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf -v
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    ports: 
      - 80:80
      - 443:443
      - 5900:5900
    volumes:
      - ./deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_MODE=1
  
  deconz-exporter:
    image: deconz-exporter
    container_name: deconz-exporter
    restart: always
    ports:
      - 9100:9100
    env_file:
      - path: secrets.env
        required: true
    environment:
      - DECONZ_PORT=80
      - DECONZ_HOST=deconz
      - DECONZ_APP_PORT=9100

  ebusd:
    image: john30/ebusd:v23.3
    container_name: ebusd
    restart: always
    links:
      - mosquitto
    depends_on:
      - mosquitto
    ports:
      - "8080:8080"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: --enablehex -d /dev/ttyUSB0 --scanconfig --mqttport=1883 --mqtthost=mosquitto --mqttjson --mqttverbose --httpport 8080

volumes:
  influxdb-storage:
  influxdb2-storage:
  influxdb2-etc-storage:
  grafana-storage:
